(function(){
 const key='wto-weekly-slip-2026';let saved=[];try{const raw=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(raw))saved=raw.filter(p=>p.season===2026)}catch(e){}
 let week=5,editId=null,activeGameId=null,focus=null,timer=null;
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const sign=x=>x==null?'Unavailable':x>0?'+'+x:String(x);
 const dialog=document.createElement('dialog');dialog.id='mySlipDialog';dialog.className='my-slip-dialog';dialog.setAttribute('aria-labelledby','mySlipTitle');document.body.append(dialog);
 const game=id=>findGame(id);
 const selectedWeek=()=>Math.max(5,Number(current)||5);
 function shell(){dialog.innerHTML=`<header><h2 id="mySlipTitle">MY SLIP ★</h2><button type="button" id="slipClose" aria-label="Close My Slip">×</button></header><p>Saved on this device. Your lines determine your results.</p><label>Week <select id="slipWeek">${Object.keys(data).filter(w=>+w>=5).map(w=>`<option value="${w}" ${+w===week?'selected':''}>Week ${w}</option>`).join('')}</select></label><label>Slip group <select id="slipGroup"><option value="">All groups</option>${[...new Set(['Favorites','1 PM','Late Games',...saved.filter(p=>p.week===week).map(p=>p.group)])].map(v=>`<option>${esc(v)}</option>`).join('')}</select></label><div id="slipList"></div><div id="slipEditor"></div><p id="slipError" role="alert"></p>`;dialog.querySelector('#slipClose').onclick=()=>dialog.close();dialog.querySelector('#slipWeek').onchange=e=>{week=+e.target.value;editId=null;shell();};dialog.querySelector('#slipGroup').onchange=list;list();}
 function list(){const group=dialog.querySelector('#slipGroup').value,rows=saved.filter(p=>p.week===week&&(!group||p.group===group)).sort((a,b)=>Date.parse(game(a.game_id)?.kickoff)-Date.parse(game(b.game_id)?.kickoff));const box=dialog.querySelector('#slipList');box.innerHTML=rows.length?rows.map(p=>{const g=game(p.game_id),lock=!g||WTOSlip.locked(g),result=WTOSlip.grade(p,g);return `<article class="slip-item"><b>${esc(g?g.away+' AT '+g.home:p.game_id)} · ${esc(p.group)}</b><p>${esc(g?.day)} · ${esc(g?.time)} ET</p><strong>${esc(p.side.toUpperCase())} ${p.kind==='winner'?'WINNER':p.kind==='spread'?sign(p.line):p.line} · ${p.custom?'CUSTOM':'SAVED MARKET'}</strong><p>Market at save: ${p.kind==='winner'?'Winner':sign(p.market_line)} · Your price: ${sign(p.price)}<br>Current: ${g?sign(WTOSlip.market(g,p.kind,p.side).line):'Unavailable'} · <b>${result}</b></p><button type="button" data-edit="${esc(p.id)}" ${lock?'disabled':''}>${lock?'LOCKED':'EDIT'}</button><button type="button" data-remove="${esc(p.id)}" ${lock?'disabled':''}>REMOVE</button>${(p.history||[]).length?`<details><summary>Earlier edits (${(p.history||[]).length})</summary>${(p.history||[]).map(h=>`<p>${esc(h.side)} ${sign(h.line)} · ${sign(h.price)} · ${esc(h.saved_at)}</p>`).join('')}</details>`:''}</article>`}).join(''):'<p>No saved picks here yet. Open a matchup and tap ★ ADD TO SLIP.</p>';box.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{const p=saved.find(p=>p.id===b.dataset.edit);editor(p.game_id,p)});box.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const p=saved.find(p=>p.id===b.dataset.remove);if(!p||WTOSlip.locked(game(p.game_id)))return;persist(saved.filter(x=>x.id!==p.id));list()});}
 function persist(next){try{localStorage.setItem(key,JSON.stringify(next));saved=next;return true}catch(e){dialog.querySelector('#slipError').textContent='Could not save on this device. Your pick was not changed.';return false}}
 function editor(id,p=null){const g=game(id);if(!g||WTOSlip.locked(g))return;editId=p?.id??null;activeGameId=id;const el=dialog.querySelector('#slipEditor');el.innerHTML=`<form id="slipForm"><h3>${esc(g.away)} AT ${esc(g.home)}</h3><label>Pick type<select id="slipKind"><option value="winner">Winner</option><option value="spread">Spread</option><option value="total">Over / Under</option></select></label><label>Side<select id="slipSide"></select></label><label id="slipLineLabel">Your line<input id="slipLine" type="number" step="0.5" inputmode="decimal"></label><p id="slipMarket"></p><button type="button" id="slipUseMarket">USE MARKET LINE</button><label>American odds (optional)<input id="slipPrice" type="number" step="1" inputmode="numeric" placeholder="Unavailable"></label><label>Slip group<input id="slipName" maxlength="40" list="slipGroups" value="${esc(p?.group??'Favorites')}"><datalist id="slipGroups"><option value="Favorites"><option value="1 PM"><option value="Late Games"></datalist></label><button type="submit">SAVE PICK ★</button><button type="button" id="slipCancel">CANCEL</button></form>`;
 const q=s=>el.querySelector(s),kind=q('#slipKind'),side=q('#slipSide'),line=q('#slipLine'),price=q('#slipPrice');kind.value=p?.kind??'winner';
 function fill(){side.innerHTML=(kind.value==='total'?['over','under']:[g.away,g.home]).map(v=>`<option value="${v}">${v.toUpperCase()}</option>`).join('');line.required=kind.value!=='winner';q('#slipLineLabel').hidden=kind.value==='winner';q('#slipUseMarket').hidden=kind.value==='winner';useMarket();}
 function marketText(){const m=WTOSlip.market(g,kind.value,side.value);q('#slipMarket').textContent=`Market line: ${sign(m.line)} · Market price: ${sign(m.price)}. Changing the line clears its price; enter your offered odds.`;}
 function useMarket(){const m=WTOSlip.market(g,kind.value,side.value);line.value=m.line??'';price.value=m.price??'';marketText()}
 kind.onchange=fill;side.onchange=useMarket;line.oninput=()=>{price.value=''};q('#slipUseMarket').onclick=useMarket;fill();if(p){side.value=p.side;line.value=p.line??'';price.value=p.price??'';marketText()}
 q('#slipCancel').onclick=()=>{el.innerHTML='';editId=null};q('#slipForm').onsubmit=e=>{e.preventDefault();dialog.querySelector('#slipError').textContent='';try{const old=editId?saved.find(x=>x.id===editId):saved.find(x=>x.game_id===g.id&&x.kind===kind.value&&x.group===q('#slipName').value.trim());const next=WTOSlip.save(old,g,{kind:kind.value,side:side.value,line:line.value,price:price.value,group:q('#slipName').value});if(persist([...saved.filter(x=>x.id!==next.id),next])){shell();}}catch(err){dialog.querySelector('#slipError').textContent=err.message}};el.scrollIntoView({block:'nearest'});}
 window.openMySlip=function(id=null){week=id?game(id)?.week??selectedWeek():selectedWeek();focus=document.activeElement;shell();if(!dialog.open)dialog.showModal();if(id)editor(id);clearInterval(timer);timer=setInterval(()=>{if(dialog.open&&dialog.querySelector('#slipEditor form')){const g=game(activeGameId);if(g&&WTOSlip.locked(g)){dialog.querySelector('#slipEditor').innerHTML='<p>This game is now locked.</p>';list()}}},1000)};
 dialog.addEventListener('close',()=>{clearInterval(timer);focus?.focus()});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
})();
