(function(){
 const key='wto-weekly-slip-2026';let saved=[];try{const raw=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(raw))saved=raw.filter(p=>p.season===2026)}catch(e){}
 let week=5,editId=null,activeGameId=null,focus=null,timer=null;
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const sign=x=>x==null?'Unavailable':x>0?'+'+x:String(x);
 const dialog=document.createElement('dialog');dialog.id='mySlipDialog';dialog.className='my-slip-dialog';dialog.setAttribute('aria-labelledby','mySlipTitle');document.body.append(dialog);
 const game=id=>findGame(id);
 const selectedWeek=()=>Math.max(5,Number(current)||5);
 function shell(){dialog.innerHTML=`<header><h2 id="mySlipTitle">MY PICK SLIP</h2><button type="button" id="slipClose" aria-label="Close My Slip">×</button></header><label>Week <select id="slipWeek">${Object.keys(data).filter(w=>+w>=5).map(w=>`<option value="${w}" ${+w===week?'selected':''}>Week ${w}</option>`).join('')}</select></label><div id="slipList"></div><p id="slipError" role="alert"></p>`;dialog.querySelector('#slipClose').onclick=()=>dialog.close();dialog.querySelector('#slipWeek').onchange=e=>{week=+e.target.value;shell()};list();}
 function list(){let last='';dialog.querySelector('#slipList').innerHTML=(data[week]||[]).map(g=>{const picks=saved.filter(p=>p.week===week&&p.game_id===g.id),lock=WTOSlip.locked(g),slot=`${g.day??''} · ${g.time??''} ET`,heading=slot!==last?`<h3 class="slip-time">${esc(slot)}</h3><div class="slip-column-head"><span>AWAY TEAM</span><span>HOME TEAM</span><span>TOTAL O/U</span></div>`:'';last=slot;
 const cell=(side,title)=>{const p=picks.find(p=>p.side===side&&p.kind!=='total');return `<div class="slip-cell ${p?'selected':''}" data-game="${esc(g.id)}" data-side="${esc(side)}"><b>${esc(side)}</b><select class="inline-kind" aria-label="${esc(side)} pick type" ${lock?'disabled':''}><option value="">No pick</option><option value="winner" ${p?.kind==='winner'?'selected':''}>Moneyline</option><option value="spread" ${p?.kind==='spread'?'selected':''}>Spread</option></select><input class="inline-line" type="number" step="0.5" aria-label="${esc(side)} custom spread" placeholder="Spread ±" value="${p?.kind==='spread'?p.line:''}" ${lock?'disabled':''}><input class="inline-price" type="number" step="1" aria-label="${esc(side)} American odds" placeholder="Odds" value="${p?.price??''}" ${lock?'disabled':''}>${p?`<small>${WTOSlip.grade(p,g)}</small>`:''}</div>`};const t=picks.find(p=>p.kind==='total');return `${heading}<div class="slip-row">${cell(g.away,'AWAY')}${cell(g.home,'HOME')}<div class="slip-cell ${t?'selected':''}" data-game="${esc(g.id)}" data-side="total"><select class="inline-kind" aria-label="Total pick" ${lock?'disabled':''}><option value="">No pick</option><option value="over" ${t?.side==='over'?'selected':''}>Over</option><option value="under" ${t?.side==='under'?'selected':''}>Under</option></select><input class="inline-line" type="number" step="0.5" aria-label="Custom total" placeholder="Total" value="${t?.line??g.total??''}" ${lock?'disabled':''}><input class="inline-price" type="number" step="1" aria-label="Total American odds" placeholder="Odds" value="${t?.price??''}" ${lock?'disabled':''}>${t?`<small>${WTOSlip.grade(t,g)}</small>`:''}</div></div>`}).join('')||'<p>No games available.</p>';
 dialog.querySelectorAll('[data-game]').forEach(cell=>{const kind=cell.querySelector('.inline-kind'),line=cell.querySelector('.inline-line'),price=cell.querySelector('.inline-price');const update=()=>{const g=game(cell.dataset.game);if(WTOSlip.locked(g))return;const total=cell.dataset.side==='total',old=saved.find(p=>p.game_id===g.id&&(total?p.kind==='total':p.side===cell.dataset.side&&p.kind!=='total'));try{dialog.querySelector('#slipError').textContent='';if(!kind.value){if(old&&persist(saved.filter(p=>p.id!==old.id)))list();return}if(!total&&kind.value==='spread'&&line.value==='')return;const next=WTOSlip.save(old,g,{kind:total?'total':kind.value,side:total?kind.value:cell.dataset.side,line:line.value,price:price.value,group:old?.group??'Favorites'});if(persist([...saved.filter(p=>p.id!==next.id),next]))list()}catch(e){dialog.querySelector('#slipError').textContent=e.message}};kind.onchange=update;line.onchange=()=>{price.value='';update()};price.onchange=update;});}
 function persist(next){try{localStorage.setItem(key,JSON.stringify(next));saved=next;return true}catch(e){dialog.querySelector('#slipError').textContent='Could not save on this device. Your pick was not changed.';return false}}
 window.openMySlip=function(id=null){week=id?game(id)?.week??selectedWeek():selectedWeek();focus=document.activeElement;shell();if(!dialog.open)dialog.showModal();clearInterval(timer);timer=setInterval(()=>{if(dialog.open)dialog.querySelectorAll('[data-game]').forEach(cell=>{if(WTOSlip.locked(game(cell.dataset.game)))cell.querySelectorAll('input,select').forEach(el=>el.disabled=true)})},1000)};
 dialog.addEventListener('close',()=>{clearInterval(timer);focus?.focus()});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
})();
