(function(){
 const key='wto-weekly-slip-2026';let saved=[];try{const raw=JSON.parse(localStorage.getItem(key)||'[]');if(Array.isArray(raw))saved=raw.filter(p=>p.season===2026)}catch(e){}
 let week=5,focus=null,timer=null,selectionMode=false;
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const sign=x=>x==null?'Unavailable':x>0?'+'+x:String(x);
 const dialog=document.createElement('dialog');dialog.id='mySlipDialog';dialog.className='my-slip-dialog';dialog.setAttribute('aria-labelledby','mySlipTitle');document.body.append(dialog);
 const game=id=>findGame(id);
 const selectedWeek=()=>Math.max(5,Number(current)||5);
 function shell(){dialog.innerHTML=`<header><h2 id="mySlipTitle">MY PICK SLIP</h2><button type="button" id="slipClose" aria-label="Close My Slip">×</button></header><label>Week <select id="slipWeek">${Object.keys(data).filter(w=>+w>=5).map(w=>`<option value="${w}" ${+w===week?'selected':''}>Week ${w}</option>`).join('')}</select></label><button type="button" id="slipViewToggle">${selectionMode?'BET/PICK LIST':'ADD / CHANGE PICKS'}</button><div id="slipList"></div><p id="slipError" role="alert"></p>`;dialog.querySelector('#slipClose').onclick=()=>dialog.close();dialog.querySelector('#slipWeek').onchange=e=>{week=+e.target.value;shell()};dialog.querySelector('#slipViewToggle').onclick=()=>{selectionMode=!selectionMode;shell()};selectionMode?list():savedList();}
 function savedList(){const picks=saved.filter(p=>p.week===week),teams=picks.filter(p=>p.kind!=='total'),totals=picks.filter(p=>p.kind==='total');const rows=teams.map(p=>({p,t:totals.find(t=>t.game_id===p.game_id)}));for(const t of totals)if(!teams.some(p=>p.game_id===t.game_id))rows.push({p:null,t});dialog.querySelector('#slipList').innerHTML=rows.length?rows.map(({p,t})=>{const g=game((p||t).game_id),lock=WTOSlip.locked(g);return `<div class="slip-saved-row"><b>${esc(p?.side??(g?g.away+'–'+g.home:'TOTAL'))}</b>${p?.kind==='winner'?'<span>ML</span>':p?`<input type="number" step="0.5" data-pick="${esc(p.id)}" aria-label="Saved spread" value="${p.line}" ${lock?'disabled':''}>`:'<span>—</span>'}${t?`<input type="number" step="0.5" data-pick="${esc(t.id)}" aria-label="Saved total" value="${t.line}" ${lock?'disabled':''}><select data-total-side="${esc(t.id)}" aria-label="Over or Under" ${lock?'disabled':''}><option value="over" ${t.side==='over'?'selected':''}>O</option><option value="under" ${t.side==='under'?'selected':''}>U</option></select>`:'<span>—</span><span></span>'}</div>`}).join(''):'<p>No saved picks yet. Tap ADD / CHANGE PICKS.</p>';dialog.querySelectorAll('[data-pick],[data-total-side]').forEach(el=>el.onchange=()=>{const p=saved.find(p=>p.id===(el.dataset.pick||el.dataset.totalSide));if(!p)return;try{const next=WTOSlip.save(p,game(p.game_id),{...p,line:el.dataset.pick?el.value:p.line,side:el.dataset.totalSide?el.value:p.side,price:el.dataset.pick?null:p.price});if(persist(saved.map(x=>x.id===p.id?next:x)))savedList()}catch(e){dialog.querySelector('#slipError').textContent=e.message}});}
 function totalDraft(id){try{return JSON.parse(localStorage.getItem('wto-slip-total-drafts')||'{}')[id]}catch(e){return null}}
 function list(){let last='';dialog.querySelector('#slipList').innerHTML=(data[week]||[]).map(g=>{const picks=saved.filter(p=>p.week===week&&p.game_id===g.id),lock=WTOSlip.locked(g),slot=`${g.day??''} · ${g.time??''} ET`,heading=slot!==last?`<h3 class="slip-time">${esc(slot)}</h3><div class="slip-table-head"><span>AWAY</span><span>SPREAD</span><span>HOME</span><span>SPREAD</span><span>TOTAL</span><span>O/U</span></div>`:'';last=slot;
 const team=(side)=>{const p=picks.find(p=>p.side===side&&p.kind!=='total'),m=WTOSlip.market(g,'spread',side);return `<button class="slip-team ${p?.kind==='winner'?'selected':''}" data-team="${esc(side)}" ${lock?'disabled':''}>${esc(side)}</button><input class="slip-number ${p?.kind==='spread'?'selected':''}" data-line="${esc(side)}" type="number" step="0.5" aria-label="${esc(side)} spread" value="${p?.kind==='spread'?p.line:m.line??''}" ${lock?'disabled':''}>`};const t=picks.find(p=>p.kind==='total');return `${heading}<div class="slip-game" data-game="${esc(g.id)}"><div class="slip-table-row">${team(g.away)}${team(g.home)}<input class="slip-number ${t?'selected':''}" data-total type="number" step="0.5" aria-label="Total" value="${t?.line??totalDraft(g.id)??g.total??''}" ${lock?'disabled':''}><select data-ou-choice aria-label="Over or Under" class="${t?'selected':''}" ${lock?'disabled':''}><option value="">—</option><option value="over" ${t?.side==='over'?'selected':''}>O</option><option value="under" ${t?.side==='under'?'selected':''}>U</option></select></div><span class="slip-result">${picks.map(p=>`${esc(p.side.toUpperCase())}: ${WTOSlip.grade(p,g)}`).join(' · ')}</span></div>`}).join('')||'<p>No games available.</p>';
 dialog.querySelectorAll('.slip-game').forEach(row=>{const g=game(row.dataset.game);function write(type,side,line,refresh=true){if(WTOSlip.locked(g))return;const old=saved.find(p=>p.game_id===g.id&&(type==='total'?p.kind==='total':p.side===side&&p.kind!=='total'));try{const next=WTOSlip.save(old,g,{kind:type,side,line,price:null,group:old?.group??'Favorites'});if(persist([...saved.filter(p=>p.id!==next.id),next])){dialog.querySelector('#slipError').textContent='';if(refresh)list();else{row.querySelectorAll('[data-line]').forEach(el=>el.classList.toggle('selected',el.dataset.line===side&&type==='spread'));if(type==='total'){row.querySelector('[data-total]').classList.add('selected');row.querySelector('[data-ou-choice]').classList.add('selected')}}}}catch(e){dialog.querySelector('#slipError').textContent=e.message}}row.querySelectorAll('[data-team]').forEach(button=>button.onclick=()=>{const side=button.dataset.team;write('winner',side,row.querySelector(`[data-line="${side}"]`).value)});row.querySelectorAll('[data-line]').forEach(input=>{input.onfocus=()=>write('spread',input.dataset.line,input.value,false);input.onchange=()=>write('spread',input.dataset.line,input.value)});row.querySelector('[data-ou-choice]').onchange=e=>{if(e.target.value)write('total',e.target.value,row.querySelector('[data-total]').value);else{const old=saved.find(p=>p.game_id===g.id&&p.kind==='total');if(old&&persist(saved.filter(p=>p.id!==old.id)))list()}};row.querySelector('[data-total]').onfocus=e=>{if(WTOSlip.locked(g))return;const side=row.querySelector('[data-ou-choice]').value;e.target.classList.add('selected');if(side)write('total',side,e.target.value,false)};row.querySelector('[data-total]').onchange=e=>{const old=saved.find(p=>p.game_id===g.id&&p.kind==='total');if(old)write('total',old.side,e.target.value);else{try{const draft=JSON.parse(localStorage.getItem('wto-slip-total-drafts')||'{}');draft[g.id]=e.target.value;localStorage.setItem('wto-slip-total-drafts',JSON.stringify(draft))}catch(err){dialog.querySelector('#slipError').textContent='Could not save this total on your device.'}}};});}
 function persist(next){try{localStorage.setItem(key,JSON.stringify(next));saved=next;return true}catch(e){dialog.querySelector('#slipError').textContent='Could not save on this device. Your pick was not changed.';return false}}
 window.openMySlip=function(id=null){week=id?game(id)?.week??selectedWeek():selectedWeek();focus=document.activeElement;selectionMode=!!id;shell();if(!dialog.open)dialog.showModal();clearInterval(timer);timer=setInterval(()=>{if(dialog.open){dialog.querySelectorAll('[data-pick],[data-total-side]').forEach(el=>{const p=saved.find(p=>p.id===(el.dataset.pick||el.dataset.totalSide));if(p&&WTOSlip.locked(game(p.game_id)))el.disabled=true});dialog.querySelectorAll('[data-game]').forEach(cell=>{if(WTOSlip.locked(game(cell.dataset.game)))cell.querySelectorAll('input,select').forEach(el=>el.disabled=true)})}},1000)};
 dialog.addEventListener('close',()=>{clearInterval(timer);focus?.focus()});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});
})();
