import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
function lib(){const c={};vm.createContext(c);vm.runInContext(fs.readFileSync(new URL('../wto-slip-lib.js',import.meta.url),'utf8'),c);return c.WTOSlip;}
const game={id:'2026-W05-TB-DAL',week:5,away:'TB',home:'DAL',kickoff:'2026-10-08T20:15:00-04:00',status:'scheduled',favorite:'DAL',spread:-8,total:47.5,awaySpreadPrice:null,homeSpreadPrice:-111};
test('custom spread grades saved side and line not live market',()=>{const l=lib(),p=l.save(null,game,{kind:'spread',side:'TB',line:3.5,price:null,group:'Favorites'},'2026-10-06T12:00:00Z');assert.equal(p.custom,true);assert.equal(p.price,null);assert.equal(l.grade(p,{...game,status:'final',awayScore:24,homeScore:27,spread:-10}),'WON');});
test('saved spread and total equality are pushes',()=>{const l=lib(),g={...game,status:'final',awayScore:20,homeScore:23};assert.equal(l.grade({kind:'spread',side:'TB',line:3},g),'PUSH');assert.equal(l.grade({kind:'total',side:'under',line:43},g),'PUSH');});
test('pregame edits preserve prior values and kickoff locks edits',()=>{const l=lib(),a=l.save(null,game,{kind:'total',side:'over',line:40,group:'1 PM'},'2026-10-06T12:00:00Z'),b=l.save(a,game,{kind:'total',side:'over',line:41,group:'1 PM'},'2026-10-06T13:00:00Z');assert.equal(b.history[0].line,40);assert.throws(()=>l.save(b,game,{kind:'total',side:'over',line:42,group:'1 PM'},game.kickoff));});
test('validates totals odds sides and season boundary',()=>{const l=lib();assert.throws(()=>l.save(null,game,{kind:'total',side:'over',line:-1},'2026-10-06T12:00:00Z'));assert.throws(()=>l.save(null,game,{kind:'winner',side:'XYZ'},'2026-10-06T12:00:00Z'));assert.throws(()=>l.save(null,game,{kind:'winner',side:'TB',price:-50},'2026-10-06T12:00:00Z'));assert.throws(()=>l.save(null,{...game,week:4},{kind:'winner',side:'TB'},'2026-10-06T12:00:00Z'));});
test('final ties push winner selections and incomplete scores remain pending',()=>{const l=lib();assert.equal(l.grade({kind:'winner',side:'TB'},{...game,status:'final',awayScore:20,homeScore:20}),'PUSH');assert.equal(l.grade({kind:'winner',side:'TB'},{...game,status:'final',awayScore:null,homeScore:20}),'PENDING');});
test('one side per market replaces opposing pick while preserving other markets',()=>{const l=lib(),a={id:'a',game_id:game.id,kind:'spread',side:'TB'},b={id:'b',game_id:game.id,kind:'spread',side:'DAL'},ml={id:'m',game_id:game.id,kind:'winner',side:'TB'},t={id:'t',game_id:game.id,kind:'total',side:'over'};const picks=l.select([a,ml,t],b);assert.equal(picks.filter(p=>p.kind==='spread').length,1);assert.equal(picks.find(p=>p.kind==='spread').side,'DAL');assert.equal(picks.length,3);assert.equal(l.select(picks,{...t,side:'under'}).filter(p=>p.kind==='total').length,1)});
test('tap selected choice again clears it and opposing choice replaces it',()=>{const l=lib();assert.equal(l.toggle('PHI','PHI'),null);assert.equal(l.toggle('PHI','JAX'),'JAX');assert.equal(l.toggle(null,'PHI'),'PHI');assert.equal(l.toggle('over','over'),null)});
