import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('../wto-ui-lib.js',import.meta.url),'utf8');
const context={};vm.createContext(context);vm.runInContext(source,context);
const {latestMarket,evaluatePredictionOutcome,selectOutcomeSummary}=context.WTOUI;
test('scheduled game uses latest ledger market instead of prediction-time market',()=>{const game={status:'scheduled',market_favorite:'IND',market_spread:-4.5,market_total:46.5,market_as_of:'2026-10-04T06:01:25-04:00',price_provider:'ScoresAndOdds'};assert.deepEqual({...latestMarket(game)},{favorite:'IND',spread:-4.5,total:46.5,market_as_of:'2026-10-04T06:01:25-04:00',provider:'ScoresAndOdds'});});
test('completed game objectively scores prediction against outcome',()=>{const game={away:'PIT',home:'CLE',awayScore:24,homeScore:27,ats:'CLE',ou:'over'};const revision={independent_projection:{winner:'PIT',away_score:21,home_score:18},market_comparison:{ats_lean:'CLE',total_lean:'UNDER'}};const result=evaluatePredictionOutcome(game,revision,{PIT:'Pittsburgh',CLE:'Cleveland'});assert.deepEqual({verdict:result.verdict,winner_correct:result.winner_correct,ats_correct:result.ats_correct,total_correct:result.total_correct,projected_score:result.projected_score,final_score:result.final_score,score_error:result.score_error,summary:result.summary},{verdict:'PARTIALLY ACCURATE',winner_correct:false,ats_correct:true,total_correct:false,projected_score:'PIT 21–18 CLE',final_score:'PIT 24–27 CLE',score_error:12,summary:'Cleveland won 27–24 after WTO projected Pittsburgh 21–18. The straight-up call missed, the CLE ATS lean hit, and the Under lean missed. The final score differed from the projection by 12 combined team points.'});});
test('no-edge calls are not counted as correct predictions',()=>{const game={away:'PIT',home:'CLE',awayScore:24,homeScore:27,ats:'CLE',ou:'over'};const revision={independent_projection:{winner:'NO EDGE',away_score:20,home_score:20},market_comparison:{ats_lean:'CLE',total_lean:'NO EDGE'}};const result=evaluatePredictionOutcome(game,revision);assert.equal(result.verdict,'PARTIALLY ACCURATE');assert.equal(result.winner_correct,null);assert.equal(result.ats_correct,true);assert.equal(result.total_correct,null);});

test('verified natural postgame recap overrides mechanical fallback',()=>{const game={postgameSummary:'Cleveland made Pittsburgh pay for its mistakes. Two interceptions and five allowed sacks kept the Steelers from taking control.'};assert.equal(selectOutcomeSummary(game,{summary:'Mechanical fallback.'}),game.postgameSummary);assert.equal(selectOutcomeSummary({}, {summary:'Mechanical fallback.'}),'Mechanical fallback.');});

test('completed quick read keeps prediction comparison without stored editorial review',()=>{const game={status:'final',away:'PIT',home:'CLE',away_score:24,home_score:27,grading_favorite:'PIT',grading_spread:-2.5,grading_total:38.5};const result={projected_score:'PIT 21–18 CLE',final_score:'PIT 24–27 CLE',verdict:'MISSED',summary:'WTO missed the winner.'};const bullets=context.WTOUI.postgameBullets(game,null,result);assert.ok(bullets.some(b=>b.text.includes('PIT 21–18 CLE')));assert.ok(bullets.some(b=>b.text.includes('MISSED')));});
