import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html=fs.readFileSync(new URL('../index.html',import.meta.url),'utf8');
const slip=fs.readFileSync(new URL('../wto-slip.js',import.meta.url),'utf8');
const code=html.slice(html.indexOf('function matchupPredictionHeader'),html.indexOf('function teamLeadersHtml'));
function setup(revision){const ctx={latestPregameInsight:()=>revision,safeText:v=>String(v??'').replaceAll('<','&lt;'),signed:v=>v>0?'+'+v:String(v),completedQuickReadHtml:()=>'<p>Verified outcome vs prediction</p>'};vm.createContext(ctx);vm.runInContext(code,ctx);return ctx}
const g={id:'x',away:'TB',home:'DAL',status:'scheduled'};
test('team read uses selected team evidence and does not invent player upside',()=>{const c=setup({factor_summary:{recent_form:'Four-game form',quarterback:{detail:'Availability unresolved'}},team_reads:{DAL:{player_upside:'Verified Dallas player upside',keys_to_compete:'Protect the pocket',watch_out:'Run defense'}},injuries:[{team:'DAL',player:'Dallas player',position:'G',status:'Limited'},{team:'TB',player:'Other player',status:'Out'}],sources:[]});assert.match(c.teamOutcomeSummary(g,'DAL'),/Protect the pocket/);assert.match(c.teamOutcomeSummary(g,'DAL'),/Dallas player · G · Limited/);assert.doesNotMatch(c.teamOutcomeSummary(g,'DAL'),/Other player/);assert.match(c.teamOutcomeSummary(g,'TB'),/Player-specific upside has not been verified/)});
test('projected score appears inside More Insight rather than the matchup pick card',()=>{const c=setup({independent_projection:{winner:'DAL',win_probability:.702,away_score:24,home_score:30},confidence:'LOW',model_audit:{probability_calibrated:false}});assert.match(c.matchupPredictionHeader(g),/TB 24–30 DAL · LOW confidence/);assert.doesNotMatch(slip,/matchupPrediction(?:Header|Insight)\(g\)/);const start=html.indexOf('async function loadMatchupMore('),end=html.indexOf(String.fromCharCode(10)+'function ',start+1),loader=html.slice(start,end);assert.ok(loader.includes('matchupPredictionHeader(g)+matchupWhyHtml(g)'));assert.doesNotMatch(c.matchupPredictionHeader(g),/projection-bar|projection-chances|Trial estimates|Uncalibrated probabilities|Locks at kickoff/);assert.match(c.teamOutcomeSummary({...g,status:'final'},'TB'),/Verified outcome vs prediction/)});

test('why details load inside More Insight instead of the pick card',()=>{const start=html.indexOf('async function loadMatchupMore('),end=html.indexOf('\nfunction ',start+1),loader=html.slice(start,end);assert.ok(start>=0);assert.equal(slip.includes('${matchupWhyHtml(g)}'),false);assert.ok(loader.includes('panel.innerHTML=matchupPredictionHeader(g)+matchupWhyHtml(g)'))});

test('matchup team blocks omit the favorite star control',()=>{const start=html.indexOf('function team(t,score)'),end=html.indexOf(String.fromCharCode(10)+'const NFL_GROUP',start),source=html.slice(start,end);assert.ok(start>=0&&end>start);assert.doesNotMatch(source,/favorite-btn|data-favorite-team|★/)});
test('NFL schedule link follows the game season and selected week',()=>{const start=html.indexOf('function nflWeekScheduleLink'),end=html.indexOf(String.fromCharCode(10)+'function ',start+1),source=html.slice(start,end),ctx={};vm.createContext(ctx);vm.runInContext(source,ctx);const out=ctx.nflWeekScheduleLink({week:5,season:2026});assert.match(out,/NFL Schedules &amp; Scores · Week 5/);assert.ok(out.includes('https://www.nfl.com/schedules/2026/by-week/reg-5'))});
test('More Insight filters WTO consensus and shows a week-aware NFL schedule link',()=>{assert.match(html,/function isWtoConsensusSource/);assert.match(html,/function verifiedEvidenceLinks/);const start=html.indexOf('async function loadMatchupMore('),end=html.indexOf(String.fromCharCode(10)+'function ',start+1),loader=html.slice(start,end);assert.ok(loader.includes('${verifiedEvidenceLinks(r,g)}'));assert.ok(html.includes('.filter(x=>!isWtoConsensusSource(x))'));assert.ok(html.includes('return links+nflWeekScheduleLink(g)'));assert.ok(!loader.includes('(r?.sources||[]).map(x=>'));assert.ok(html.includes('!isWtoConsensusSource(x)'))});
test('inline application scripts stay syntactically valid',()=>{const blocks=html.split('<script').slice(1).map(x=>x.slice(x.indexOf('>')+1,x.indexOf('</script>')));for(const block of blocks)assert.doesNotThrow(()=>new vm.Script(block))});
test('startup opens the weekly summary home screen',()=>{assert.match(html,/<div class="summary-screen" id="summaryScreen">/);assert.match(html,/<div class="screen app-hidden" id="trackerScreen">/)});
test('scheduled team blocks omit the empty dash placeholder',()=>{const start=html.indexOf('function team(t,score)'),end=html.indexOf(String.fromCharCode(10)+'const NFL_GROUP',start),source=html.slice(start,end),ctx={TEAM:{TB:['Tampa Bay','#c00','tb']},current:5,logo:()=>'/logo.png'};vm.createContext(ctx);vm.runInContext(source,ctx);assert.doesNotMatch(ctx.team('TB',null),/—/);assert.match(ctx.team('TB',24),/Score · 24/)});
